# Generated by Django 4.2.3 on 2023-07-11 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_created_at_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 9, 31, 38, 150564, tzinfo=datetime.timezone.utc)),
        ),
    ]
