# Generated by Django 4.2.3 on 2023-07-15 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_created_at_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 16, 0, 0, 896460, tzinfo=datetime.timezone.utc)),
        ),
    ]
