# Generated by Django 4.2.3 on 2023-07-16 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 4, 21, 32, 510149, tzinfo=datetime.timezone.utc)),
        ),
    ]
