# Generated by Django 4.2.3 on 2023-07-18 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 16, 3, 35, 903257, tzinfo=datetime.timezone.utc)),
        ),
    ]
