# Generated by Django 4.2.3 on 2023-07-19 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 4, 56, 51, 406456, tzinfo=datetime.timezone.utc)),
        ),
    ]
