# Generated by Django 4.2.3 on 2023-07-27 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_coupon_alter_cart_created_at_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 6, 10, 25, 441160, tzinfo=datetime.timezone.utc)),
        ),
    ]
