# Generated by Django 4.2.3 on 2023-07-27 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cart_total_price_alter_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 6, 33, 27, 39506, tzinfo=datetime.timezone.utc)),
        ),
    ]
