# Generated by Django 4.2.3 on 2023-07-27 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_cartitem_coupon_alter_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 7, 12, 38, 967327, tzinfo=datetime.timezone.utc)),
        ),
    ]
