# Generated by Django 4.2.3 on 2023-07-28 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_cart_coupon_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 8, 26, 40, 921746, tzinfo=datetime.timezone.utc)),
        ),
    ]
