# Generated by Django 4.2.3 on 2023-07-30 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 5, 4, 18, 552841, tzinfo=datetime.timezone.utc)),
        ),
    ]
