# Generated by Django 4.2.3 on 2023-08-03 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 6, 48, 10, 220222, tzinfo=datetime.timezone.utc)),
        ),
    ]
