# Generated by Django 4.2.3 on 2023-07-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
