# Generated by Django 4.2.3 on 2023-08-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'razorpay'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('PAY USING WALLET', 'pay using wallet')], max_length=20),
        ),
    ]
