# Generated by Django 4.2.3 on 2023-07-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorytable',
            table='store_categorytable',
        ),
    ]
