# Generated by Django 4.2.3 on 2023-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_useraddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
