# Generated by Django 4.2.3 on 2023-07-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_useraddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
