# Generated by Django 4.2.3 on 2023-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_userwallet_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
