from django.urls import path
from . import views

urlpatterns = [
    path('_admin', views.admin_login, name='admin_login'),
    path('admin-home', views.home, name='admin_home'),
    path('sales-report', views.download_sales_report, name='download_sales_report'),
    path('user-details', views.userdetails, name='user_details'),
    path('block-user/<int:id>/', views.block_user, name='block_user'),
    path('unblock-user/<int:id>/', views.unblock_user, name='unblock_user'),
    path('admin-logout', views.admin_logout, name='admin_logout'),
    path('category', views.category, name='category'),
    path('add-category', views.add_category, name='add_category'),
    path('disable-category/<int:id>', views.disable_category, name='disable_category'),
    path('enable-category/<int:id>', views.enable_category, name='enable_category'),
    path('products', views.products, name='products'),
    path('view-product/<int:product_id>', views.view_product, name='view_product'),
    path('add-product', views.add_product, name='add_product'),
    path('add-variant/<int:product_id>', views.add_variant, name='add_variant'),
    path('disable-variant/<int:variant_id>', views.disable_variant, name='disable_variant'),
    path('enable-variant/<int:variant_id>', views.enable_variant, name='enable_variant'),
    path('disable-product/<int:product_id>', views.disable_product, name='disable_product'),
    path('enable-product/<int:product_id>', views.enable_product, name='enable_product'),
    path('edit-category/<int:category_id>', views.edit_category, name='edit_category'),
    path('edit-product/<int:product_id>', views.edit_product, name='edit_product'),
    path('edit-variant/<int:variant_id>', views.edit_variant, name='edit_variant'),
    path('orders',views.orders,name='orders'),
    path('user-order-details/<int:order_id>', views.user_order_detail, name='user_order_details'),
    path('user-order-cancellation/<int:order_id>', views.user_order_cancellation, name='user_order_cancellation'),
    path('order-invoice/<int:order_id>', views.user_order_invoice, name='user_order_invoice'),
    path('download_invoice/<int:order_id>', views.download_user_invoice, name='download_user_invoice'),
    path('change-status/<int:order_id>', views.change_status, name='change_status'),
    path('add-coupon', views.add_coupon, name='add_coupon'),
    path('coupons', views.list_coupon, name='coupons'),
    path('edit-coupon/<int:coupon_id>', views.edit_coupon, name='edit_coupon'),
    path('user-order-returned/<int:order_id>', views.user_order_returned, name='user_order_returned'),
    path('add-brand', views.add_brand, name='add_brand'),
    path('brands', views.brands, name='brands')
]
